<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Item/ApkDetail.proto

namespace GPBMetadata\Item;

class ApkDetail
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x99\x02\x0A\x14Item/ApkDetail.proto\x12\x0DtbClient.item\"\xE9\x01\x0A\x09ApkDetail\x12\x11\x0A\x09developer\x18\x01 \x01(\x09\x12\x11\x0A\x09publisher\x18\x02 \x01(\x09\x12\x0F\x0A\x07version\x18\x03 \x01(\x09\x12\x14\x0A\x0Cversion_code\x18\x06 \x01(\x05\x12\x13\x0A\x0Bupdate_time\x18\x07 \x01(\x09\x12\x0C\x0A\x04size\x18\x08 \x01(\x09\x12\x14\x0A\x0Cneed_network\x18\x09 \x01(\x05\x12\x16\x0A\x0Eneed_inner_buy\x18\x0A \x01(\x05\x12\x15\x0A\x0Dauthority_url\x18\x0B \x01(\x09\x12\x13\x0A\x0Bprivacy_url\x18\x0C \x01(\x09\x12\x12\x0A\x0Apkg_source\x18\x0D \x01(\x05b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

