<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserDeps/Icon.proto

namespace TbClient\UserDeps;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.userDeps.Icon</code>
 */
class Icon extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 weight = 2;</code>
     */
    protected $weight = 0;
    /**
     * Generated from protobuf field <code>string url = 3;</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>string icon = 4;</code>
     */
    protected $icon = '';
    /**
     * Generated from protobuf field <code>int32 value = 5;</code>
     */
    protected $value = 0;
    /**
     * Generated from protobuf field <code>.tbClient.userDeps.Icon.Terminal terminal = 6;</code>
     */
    protected $terminal = null;
    /**
     * Generated from protobuf field <code>.tbClient.userDeps.Icon.Position position = 7;</code>
     */
    protected $position = null;
    /**
     * Generated from protobuf field <code>repeated string sprite_info = 8;</code>
     */
    private $sprite_info;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $weight
     *     @type string $url
     *     @type string $icon
     *     @type int $value
     *     @type \TbClient\UserDeps\Icon\Terminal $terminal
     *     @type \TbClient\UserDeps\Icon\Position $position
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $sprite_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserDeps\Icon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 2;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 3;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 4;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 value = 5;</code>
     * @return int
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>int32 value = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tbClient.userDeps.Icon.Terminal terminal = 6;</code>
     * @return \TbClient\UserDeps\Icon\Terminal|null
     */
    public function getTerminal()
    {
        return $this->terminal;
    }

    public function hasTerminal()
    {
        return isset($this->terminal);
    }

    public function clearTerminal()
    {
        unset($this->terminal);
    }

    /**
     * Generated from protobuf field <code>.tbClient.userDeps.Icon.Terminal terminal = 6;</code>
     * @param \TbClient\UserDeps\Icon\Terminal $var
     * @return $this
     */
    public function setTerminal($var)
    {
        GPBUtil::checkMessage($var, \TbClient\UserDeps\Icon\Terminal::class);
        $this->terminal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tbClient.userDeps.Icon.Position position = 7;</code>
     * @return \TbClient\UserDeps\Icon\Position|null
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function hasPosition()
    {
        return isset($this->position);
    }

    public function clearPosition()
    {
        unset($this->position);
    }

    /**
     * Generated from protobuf field <code>.tbClient.userDeps.Icon.Position position = 7;</code>
     * @param \TbClient\UserDeps\Icon\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \TbClient\UserDeps\Icon\Position::class);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string sprite_info = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpriteInfo()
    {
        return $this->sprite_info;
    }

    /**
     * Generated from protobuf field <code>repeated string sprite_info = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpriteInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->sprite_info = $arr;

        return $this;
    }

}

