<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/Common/Content.proto

namespace GPBMetadata\Post\Common;

class Content
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Item\Item::initOnce();
        \GPBMetadata\Post\Common\TiebaPlusInfo::initOnce();
        \GPBMetadata\Post\Common\TogetherHi::initOnce();
        $pool->internalAddGeneratedFile(
            '
ö

Post/Common/Content.prototbClient.post.commonPost/Common/TiebaPlusInfo.protoPost/Common/TogetherHi.proto"û	
Content
type (
text (	
link (	
src (	
bsize (	
big_src (	
big_size (	
cdn_src (	
big_cdn_src	 (	
imgtype
 (		
c (	
	voice_md5 (	
during_time (
is_sub (
uid (
dynamic (	
_static (	
width (
height (
packet_name (	
	phonetype (	
is_native_app (;

native_app (2\'.tbClient.post.common.Content.NativeApp
e_type (

origin_src (	
btn_type (
origin_size (
count (A
graffiti_info (2*.tbClient.post.common.Content.GraffitiInfo7
high_together (2 .tbClient.post.common.TogetherHi
media_subtitle (	
url_type  (9
	meme_info! (2&.tbClient.post.common.Content.MemeInfo
is_long_pic" (
show_original_btn# (
cdn_src_active$ (	
topic_special_icon% (	
item_id& (
item_forum_name\' (	;
tiebaplus_info( (2#.tbClient.post.common.TiebaPlusInfo!
item) (2.tbClient.item.Item
pic_id* ([
	NativeApp
jump_and (	
jump_ios (	
download_and (	
download_ios (	(
GraffitiInfo
url (	
gid (‚
MemeInfo
pck_id (
pic_id (
pic_url (	
	thumbnail (	
width (
height (
detail_link (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

