<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Post/Common/Abstract.proto

namespace GPBMetadata\Post\Common;

class PBAbstract
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB1\x01\x0A\x1APost/Common/Abstract.proto\x12\x14tbClient.post.common\"u\x0A\x08Abstract\x12\x0C\x0A\x04type\x18\x01 \x01(\x05\x12\x0C\x0A\x04text\x18\x02 \x01(\x09\x12\x0C\x0A\x04link\x18\x03 \x01(\x09\x12\x0B\x0A\x03src\x18\x04 \x01(\x09\x12\x0A\x0A\x02un\x18\x05 \x01(\x09\x12\x13\x0A\x0Bduring_time\x18\x06 \x01(\x09\x12\x11\x0A\x09voice_md5\x18\x07 \x01(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

