<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Post/Common/Zan.proto

namespace GPBMetadata\Post\Common;

class Zan
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\User::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBB\x01\x0A\x15Post/Common/Zan.proto\x12\x14tbClient.post.common\"\x83\x01\x0A\x03Zan\x12\x0B\x0A\x03num\x18\x01 \x01(\x05\x12\"\x0A\x0Aliker_list\x18\x02 \x03(\x0B2\x0E.tbClient.User\x12\x10\x0A\x08is_liked\x18\x03 \x01(\x05\x12\x11\x0A\x09last_time\x18\x04 \x01(\x05\x12\x10\x0A\x08liker_id\x18\x05 \x03(\x03\x12\x14\x0A\x0Cconsent_type\x18\x06 \x01(\x05b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

