<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Revision/ReplyRevisionNullFields.proto

namespace GPBMetadata\Revision;

class ReplyRevisionNullFields
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ð
&Revision/ReplyRevisionNullFields.prototbClient.revision"ª
ReplyRevisionNullFields
authorManagerType (
authorExpGrade (
subReplyNum (
isFold (
agreeNum (
disagreeNum (
location (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

