<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Revision/ThreadRevisionNullFields.proto

namespace GPBMetadata\Revision;

class ThreadRevisionNullFields
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
»
\'Revision/ThreadRevisionNullFields.prototbClient.revision"ô
ThreadRevisionNullFields

stickyType (
	topicType (
isGood (
authorManagerType (
latestReplierUid (
replyNum (
viewNum	 (
shareNum
 (
agreeNum (
disagreeNum (
location (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

