<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Api/Response/SubReplyResponse.proto

namespace TbClient\Api\Response\SubReplyResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.api.response.SubReplyResponse.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.tbClient.Page page = 1;</code>
     */
    protected $page = null;
    /**
     * Generated from protobuf field <code>repeated .tbClient.post.SubReply subpost_list = 4;</code>
     */
    private $subpost_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TbClient\Page $page
     *     @type array<\TbClient\Post\SubReply>|\Google\Protobuf\Internal\RepeatedField $subpost_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\Response\SubReplyResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.tbClient.Page page = 1;</code>
     * @return \TbClient\Page|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>.tbClient.Page page = 1;</code>
     * @param \TbClient\Page $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \TbClient\Page::class);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .tbClient.post.SubReply subpost_list = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubpostList()
    {
        return $this->subpost_list;
    }

    /**
     * Generated from protobuf field <code>repeated .tbClient.post.SubReply subpost_list = 4;</code>
     * @param array<\TbClient\Post\SubReply>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubpostList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TbClient\Post\SubReply::class);
        $this->subpost_list = $arr;

        return $this;
    }

}

