<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Item/ApkDetail.proto

namespace GPBMetadata\Item;

class ApkDetail
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
™
Item/ApkDetail.prototbClient.item"é
	ApkDetail
	developer (	
	publisher (	
version (	
version_code (
update_time (	
size (	
need_network	 (
need_inner_buy
 (
authority_url (	
privacy_url (	

pkg_source (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

