<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Item/Item.proto

namespace GPBMetadata\Item;

class Item
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Item\ApkDetail::initOnce();
        $pool->internalAddGeneratedFile(
            '
æ
Item/Item.prototbClient.item"»
Item
item_id (
	item_name (	
	icon_size (
icon_url (	
tags (	
score (
star (
button_name (	
button_link	 (	

item_appid
 (	
category_id (
button_link_type (
apk_name (	

forum_name (	,

apk_detail (2.tbClient.item.ApkDetailbproto3'
        , true);

        static::$is_initialized = true;
    }
}

