// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Post/SubReply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TbClient.Post {

  /// <summary>Holder for reflection information generated from Post/SubReply.proto</summary>
  public static partial class SubReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for Post/SubReply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SubReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQb3N0L1N1YlJlcGx5LnByb3RvEg10YkNsaWVudC5wb3N0GhdQb3N0L0Nv",
            "bW1vbi9BZ3JlZS5wcm90bxoVUG9zdC9Db21tb24vTGJzLnByb3RvGhlQb3N0",
            "L0NvbW1vbi9Db250ZW50LnByb3RvGgpVc2VyLnByb3RvIsICCghTdWJSZXBs",
            "eRIMCgRzcGlkGAEgASgEEi4KB2NvbnRlbnQYAiADKAsyHS50YkNsaWVudC5w",
            "b3N0LmNvbW1vbi5Db250ZW50EgwKBHRpbWUYAyABKA0SEQoJYXV0aG9yX2lk",
            "GAQgASgDEg0KBXRpdGxlGAUgASgJEg0KBWZsb29yGAYgASgNEh4KBmF1dGhv",
            "chgHIAEoCzIOLnRiQ2xpZW50LlVzZXISEwoLaXNfZ2lmdHBvc3QYCCABKAUS",
            "KgoFYWdyZWUYCSABKAsyGy50YkNsaWVudC5wb3N0LmNvbW1vbi5BZ3JlZRIr",
            "Cghsb2NhdGlvbhgKIAEoCzIZLnRiQ2xpZW50LnBvc3QuY29tbW9uLkxicxIT",
            "Cgtpc19mYWtlX3RvcBgLIAEoBRIWCg5pc19hdXRob3JfdmlldxgMIAEoBWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TbClient.Post.Common.AgreeReflection.Descriptor, global::TbClient.Post.Common.LbsReflection.Descriptor, global::TbClient.Post.Common.ContentReflection.Descriptor, global::TbClient.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TbClient.Post.SubReply), global::TbClient.Post.SubReply.Parser, new[]{ "Spid", "Content", "Time", "AuthorId", "Title", "Floor", "Author", "IsGiftpost", "Agree", "Location", "IsFakeTop", "IsAuthorView" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SubReply : pb::IMessage<SubReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SubReply> _parser = new pb::MessageParser<SubReply>(() => new SubReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SubReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TbClient.Post.SubReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubReply(SubReply other) : this() {
      spid_ = other.spid_;
      content_ = other.content_.Clone();
      time_ = other.time_;
      authorId_ = other.authorId_;
      title_ = other.title_;
      floor_ = other.floor_;
      author_ = other.author_ != null ? other.author_.Clone() : null;
      isGiftpost_ = other.isGiftpost_;
      agree_ = other.agree_ != null ? other.agree_.Clone() : null;
      location_ = other.location_ != null ? other.location_.Clone() : null;
      isFakeTop_ = other.isFakeTop_;
      isAuthorView_ = other.isAuthorView_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubReply Clone() {
      return new SubReply(this);
    }

    /// <summary>Field number for the "spid" field.</summary>
    public const int SpidFieldNumber = 1;
    private ulong spid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Spid {
      get { return spid_; }
      set {
        spid_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    private static readonly pb::FieldCodec<global::TbClient.Post.Common.Content> _repeated_content_codec
        = pb::FieldCodec.ForMessage(18, global::TbClient.Post.Common.Content.Parser);
    private readonly pbc::RepeatedField<global::TbClient.Post.Common.Content> content_ = new pbc::RepeatedField<global::TbClient.Post.Common.Content>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TbClient.Post.Common.Content> Content {
      get { return content_; }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 3;
    private uint time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "author_id" field.</summary>
    public const int AuthorIdFieldNumber = 4;
    private long authorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AuthorId {
      get { return authorId_; }
      set {
        authorId_ = value;
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 5;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "floor" field.</summary>
    public const int FloorFieldNumber = 6;
    private uint floor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Floor {
      get { return floor_; }
      set {
        floor_ = value;
      }
    }

    /// <summary>Field number for the "author" field.</summary>
    public const int AuthorFieldNumber = 7;
    private global::TbClient.User author_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TbClient.User Author {
      get { return author_; }
      set {
        author_ = value;
      }
    }

    /// <summary>Field number for the "is_giftpost" field.</summary>
    public const int IsGiftpostFieldNumber = 8;
    private int isGiftpost_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsGiftpost {
      get { return isGiftpost_; }
      set {
        isGiftpost_ = value;
      }
    }

    /// <summary>Field number for the "agree" field.</summary>
    public const int AgreeFieldNumber = 9;
    private global::TbClient.Post.Common.Agree agree_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TbClient.Post.Common.Agree Agree {
      get { return agree_; }
      set {
        agree_ = value;
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 10;
    private global::TbClient.Post.Common.Lbs location_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TbClient.Post.Common.Lbs Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "is_fake_top" field.</summary>
    public const int IsFakeTopFieldNumber = 11;
    private int isFakeTop_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsFakeTop {
      get { return isFakeTop_; }
      set {
        isFakeTop_ = value;
      }
    }

    /// <summary>Field number for the "is_author_view" field.</summary>
    public const int IsAuthorViewFieldNumber = 12;
    private int isAuthorView_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsAuthorView {
      get { return isAuthorView_; }
      set {
        isAuthorView_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SubReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SubReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Spid != other.Spid) return false;
      if(!content_.Equals(other.content_)) return false;
      if (Time != other.Time) return false;
      if (AuthorId != other.AuthorId) return false;
      if (Title != other.Title) return false;
      if (Floor != other.Floor) return false;
      if (!object.Equals(Author, other.Author)) return false;
      if (IsGiftpost != other.IsGiftpost) return false;
      if (!object.Equals(Agree, other.Agree)) return false;
      if (!object.Equals(Location, other.Location)) return false;
      if (IsFakeTop != other.IsFakeTop) return false;
      if (IsAuthorView != other.IsAuthorView) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Spid != 0UL) hash ^= Spid.GetHashCode();
      hash ^= content_.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      if (AuthorId != 0L) hash ^= AuthorId.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Floor != 0) hash ^= Floor.GetHashCode();
      if (author_ != null) hash ^= Author.GetHashCode();
      if (IsGiftpost != 0) hash ^= IsGiftpost.GetHashCode();
      if (agree_ != null) hash ^= Agree.GetHashCode();
      if (location_ != null) hash ^= Location.GetHashCode();
      if (IsFakeTop != 0) hash ^= IsFakeTop.GetHashCode();
      if (IsAuthorView != 0) hash ^= IsAuthorView.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Spid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Spid);
      }
      content_.WriteTo(output, _repeated_content_codec);
      if (Time != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Time);
      }
      if (AuthorId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(AuthorId);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Title);
      }
      if (Floor != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Floor);
      }
      if (author_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Author);
      }
      if (IsGiftpost != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(IsGiftpost);
      }
      if (agree_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Agree);
      }
      if (location_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Location);
      }
      if (IsFakeTop != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(IsFakeTop);
      }
      if (IsAuthorView != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(IsAuthorView);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Spid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Spid);
      }
      content_.WriteTo(ref output, _repeated_content_codec);
      if (Time != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Time);
      }
      if (AuthorId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(AuthorId);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Title);
      }
      if (Floor != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Floor);
      }
      if (author_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Author);
      }
      if (IsGiftpost != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(IsGiftpost);
      }
      if (agree_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Agree);
      }
      if (location_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Location);
      }
      if (IsFakeTop != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(IsFakeTop);
      }
      if (IsAuthorView != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(IsAuthorView);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Spid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Spid);
      }
      size += content_.CalculateSize(_repeated_content_codec);
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
      }
      if (AuthorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AuthorId);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Floor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Floor);
      }
      if (author_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Author);
      }
      if (IsGiftpost != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsGiftpost);
      }
      if (agree_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Agree);
      }
      if (location_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Location);
      }
      if (IsFakeTop != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsFakeTop);
      }
      if (IsAuthorView != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsAuthorView);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SubReply other) {
      if (other == null) {
        return;
      }
      if (other.Spid != 0UL) {
        Spid = other.Spid;
      }
      content_.Add(other.content_);
      if (other.Time != 0) {
        Time = other.Time;
      }
      if (other.AuthorId != 0L) {
        AuthorId = other.AuthorId;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Floor != 0) {
        Floor = other.Floor;
      }
      if (other.author_ != null) {
        if (author_ == null) {
          Author = new global::TbClient.User();
        }
        Author.MergeFrom(other.Author);
      }
      if (other.IsGiftpost != 0) {
        IsGiftpost = other.IsGiftpost;
      }
      if (other.agree_ != null) {
        if (agree_ == null) {
          Agree = new global::TbClient.Post.Common.Agree();
        }
        Agree.MergeFrom(other.Agree);
      }
      if (other.location_ != null) {
        if (location_ == null) {
          Location = new global::TbClient.Post.Common.Lbs();
        }
        Location.MergeFrom(other.Location);
      }
      if (other.IsFakeTop != 0) {
        IsFakeTop = other.IsFakeTop;
      }
      if (other.IsAuthorView != 0) {
        IsAuthorView = other.IsAuthorView;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Spid = input.ReadUInt64();
            break;
          }
          case 18: {
            content_.AddEntriesFrom(input, _repeated_content_codec);
            break;
          }
          case 24: {
            Time = input.ReadUInt32();
            break;
          }
          case 32: {
            AuthorId = input.ReadInt64();
            break;
          }
          case 42: {
            Title = input.ReadString();
            break;
          }
          case 48: {
            Floor = input.ReadUInt32();
            break;
          }
          case 58: {
            if (author_ == null) {
              Author = new global::TbClient.User();
            }
            input.ReadMessage(Author);
            break;
          }
          case 64: {
            IsGiftpost = input.ReadInt32();
            break;
          }
          case 74: {
            if (agree_ == null) {
              Agree = new global::TbClient.Post.Common.Agree();
            }
            input.ReadMessage(Agree);
            break;
          }
          case 82: {
            if (location_ == null) {
              Location = new global::TbClient.Post.Common.Lbs();
            }
            input.ReadMessage(Location);
            break;
          }
          case 88: {
            IsFakeTop = input.ReadInt32();
            break;
          }
          case 96: {
            IsAuthorView = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Spid = input.ReadUInt64();
            break;
          }
          case 18: {
            content_.AddEntriesFrom(ref input, _repeated_content_codec);
            break;
          }
          case 24: {
            Time = input.ReadUInt32();
            break;
          }
          case 32: {
            AuthorId = input.ReadInt64();
            break;
          }
          case 42: {
            Title = input.ReadString();
            break;
          }
          case 48: {
            Floor = input.ReadUInt32();
            break;
          }
          case 58: {
            if (author_ == null) {
              Author = new global::TbClient.User();
            }
            input.ReadMessage(Author);
            break;
          }
          case 64: {
            IsGiftpost = input.ReadInt32();
            break;
          }
          case 74: {
            if (agree_ == null) {
              Agree = new global::TbClient.Post.Common.Agree();
            }
            input.ReadMessage(Agree);
            break;
          }
          case 82: {
            if (location_ == null) {
              Location = new global::TbClient.Post.Common.Lbs();
            }
            input.ReadMessage(Location);
            break;
          }
          case 88: {
            IsFakeTop = input.ReadInt32();
            break;
          }
          case 96: {
            IsAuthorView = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
