<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/SubReply.proto

namespace TbClient\Post;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.post.SubReply</code>
 */
class SubReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 spid = 1;</code>
     */
    protected $spid = 0;
    /**
     * Generated from protobuf field <code>repeated .tbClient.post.common.Content content = 2;</code>
     */
    private $content;
    /**
     * Generated from protobuf field <code>uint32 time = 3;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>.tbClient.User author = 7;</code>
     */
    protected $author = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $spid
     *     @type array<\TbClient\Post\Common\Content>|\Google\Protobuf\Internal\RepeatedField $content
     *     @type int $time
     *     @type \TbClient\User $author
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Post\SubReply::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 spid = 1;</code>
     * @return int|string
     */
    public function getSpid()
    {
        return $this->spid;
    }

    /**
     * Generated from protobuf field <code>uint64 spid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpid($var)
    {
        GPBUtil::checkUint64($var);
        $this->spid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .tbClient.post.common.Content content = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>repeated .tbClient.post.common.Content content = 2;</code>
     * @param array<\TbClient\Post\Common\Content>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContent($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TbClient\Post\Common\Content::class);
        $this->content = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 time = 3;</code>
     * @return int
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>uint32 time = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tbClient.User author = 7;</code>
     * @return \TbClient\User|null
     */
    public function getAuthor()
    {
        return $this->author;
    }

    public function hasAuthor()
    {
        return isset($this->author);
    }

    public function clearAuthor()
    {
        unset($this->author);
    }

    /**
     * Generated from protobuf field <code>.tbClient.User author = 7;</code>
     * @param \TbClient\User $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkMessage($var, \TbClient\User::class);
        $this->author = $var;

        return $this;
    }

}

