<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Api/Response/ReplyResponse.proto

namespace GPBMetadata\Api\Response;

class ReplyResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Post\Reply::initOnce();
        \GPBMetadata\Forum\SimpleForum::initOnce();
        \GPBMetadata\Error::initOnce();
        \GPBMetadata\Page::initOnce();
        \GPBMetadata\User::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x89\x03\x0A Api/Response/ReplyResponse.proto\x12\x15tbClient.api.response\x1A\x17Forum/SimpleForum.proto\x1A\x0BError.proto\x1A\x0APage.proto\x1A\x0AUser.proto\"\x87\x02\x0A\x0DReplyResponse\x12\x1E\x0A\x05error\x18\x01 \x01(\x0B2\x0F.tbClient.Error\x127\x0A\x04data\x18\x02 \x01(\x0B2).tbClient.api.response.ReplyResponse.Data\x1A\x9C\x01\x0A\x04Data\x12\x1C\x0A\x04page\x18\x03 \x01(\x0B2\x0E.tbClient.Page\x12*\x0A\x05forum\x18\x02 \x01(\x0B2\x1B.tbClient.forum.SimpleForum\x12'\x0A\x09post_list\x18\x06 \x03(\x0B2\x14.tbClient.post.Reply\x12!\x0A\x09user_list\x18\x0D \x03(\x0B2\x0E.tbClient.Userb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

