<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: User.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserDeps\Icon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB1\x02\x0A\x0AUser.proto\x12\x08tbClient\"\x90\x02\x0A\x04User\x12\x0B\x0A\x03uid\x18\x02 \x01(\x03\x12\x0C\x0A\x04name\x18\x03 \x01(\x09\x12\x11\x0A\x09name_show\x18\x04 \x01(\x09\x12\x10\x0A\x08portrait\x18\x05 \x01(\x09\x12)\x0A\x08iconinfo\x18\x11 \x03(\x0B2\x17.tbClient.userDeps.Icon\x12\x10\x0A\x08level_id\x18\x17 \x01(\x05\x12\x0E\x0A\x06gender\x18* \x01(\x05\x12\x15\x0A\x0Dfans_nickname\x189 \x01(\x09\x12,\x0A\x08ala_info\x18N \x01(\x0B2\x1A.tbClient.User.AlaUserInfo\x12\x12\x0A\x0Aip_address\x18\x7F \x01(\x09\x1A\"\x0A\x0BAlaUserInfo\x12\x13\x0A\x0Blive_status\x18\x08 \x01(\x0Db\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

