<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Post/SubReply.proto

namespace GPBMetadata\Post;

class SubReply
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Post\Common\Content::initOnce();
        \GPBMetadata\Post\Common\Agree::initOnce();
        \GPBMetadata\User::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF6\x01\x0A\x13Post/SubReply.proto\x12\x0DtbClient.post\x1A\x17Post/Common/Agree.proto\x1A\x0AUser.proto\"\xA2\x01\x0A\x08SubReply\x12\x0C\x0A\x04spid\x18\x01 \x01(\x04\x12.\x0A\x07content\x18\x02 \x03(\x0B2\x1D.tbClient.post.common.Content\x12\x0C\x0A\x04time\x18\x03 \x01(\x0D\x12\x1E\x0A\x06author\x18\x07 \x01(\x0B2\x0E.tbClient.User\x12*\x0A\x05agree\x18\x09 \x01(\x0B2\x1B.tbClient.post.common.Agreeb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

