<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/Thread.proto

namespace GPBMetadata\Post;

class Thread
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\User::initOnce();
        \GPBMetadata\Post\Common\Zan::initOnce();
        \GPBMetadata\Post\Common\Lbs::initOnce();
        \GPBMetadata\Post\Common\Agree::initOnce();
        $pool->internalAddGeneratedFile(
            '

Post/Thread.prototbClient.postPost/Common/Zan.protoPost/Common/Lbs.protoPost/Common/Agree.proto"©
Thread
tid (
title (	
	reply_num (
view_num (
last_time_int (
thread_types (
is_top	 (
is_good
 (
author (2.tbClient.User$
last_replyer (2.tbClient.User1
	_abstract (2.tbClient.post.Thread.Abstract
fid (
live_post_type (	
first_post_id( (&
zan) (2.tbClient.post.common.Zan
create_time- (
is_membertop6 (
	author_id8 (+
location> (2.tbClient.post.common.Lbs
	agree_num| (*
agree~ (2.tbClient.post.common.Agree
	share_num‡ (u
Abstract
type (
text (	
link (	
src (	

un (	
during_time (	
	voice_md5 (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

