<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Post/Common/Content.proto

namespace TbClient\Post\Common\Content;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.post.common.Content.NativeApp</code>
 */
class NativeApp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string jump_and = 1;</code>
     */
    protected $jump_and = '';
    /**
     * Generated from protobuf field <code>string jump_ios = 2;</code>
     */
    protected $jump_ios = '';
    /**
     * Generated from protobuf field <code>string download_and = 3;</code>
     */
    protected $download_and = '';
    /**
     * Generated from protobuf field <code>string download_ios = 4;</code>
     */
    protected $download_ios = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $jump_and
     *     @type string $jump_ios
     *     @type string $download_and
     *     @type string $download_ios
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Post\Common\Content::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string jump_and = 1;</code>
     * @return string
     */
    public function getJumpAnd()
    {
        return $this->jump_and;
    }

    /**
     * Generated from protobuf field <code>string jump_and = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJumpAnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->jump_and = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jump_ios = 2;</code>
     * @return string
     */
    public function getJumpIos()
    {
        return $this->jump_ios;
    }

    /**
     * Generated from protobuf field <code>string jump_ios = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJumpIos($var)
    {
        GPBUtil::checkString($var, True);
        $this->jump_ios = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string download_and = 3;</code>
     * @return string
     */
    public function getDownloadAnd()
    {
        return $this->download_and;
    }

    /**
     * Generated from protobuf field <code>string download_and = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadAnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_and = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string download_ios = 4;</code>
     * @return string
     */
    public function getDownloadIos()
    {
        return $this->download_ios;
    }

    /**
     * Generated from protobuf field <code>string download_ios = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadIos($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_ios = $var;

        return $this;
    }

}

