<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/Common/Content.proto

namespace TbClient\Post\Common\Content;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.post.common.Content.TiebaPlusInfo</code>
 */
class TiebaPlusInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string desc = 2;</code>
     */
    protected $desc = '';
    /**
     * Generated from protobuf field <code>string jump_url = 3;</code>
     */
    protected $jump_url = '';
    /**
     * Generated from protobuf field <code>string download_url = 4;</code>
     */
    protected $download_url = '';
    /**
     * Generated from protobuf field <code>string app_id = 5;</code>
     */
    protected $app_id = '';
    /**
     * Generated from protobuf field <code>string app_icon = 6;</code>
     */
    protected $app_icon = '';
    /**
     * Generated from protobuf field <code>string app_package = 7;</code>
     */
    protected $app_package = '';
    /**
     * Generated from protobuf field <code>string app_version = 8;</code>
     */
    protected $app_version = '';
    /**
     * Generated from protobuf field <code>string app_privacy = 9;</code>
     */
    protected $app_privacy = '';
    /**
     * Generated from protobuf field <code>string app_power = 10;</code>
     */
    protected $app_power = '';
    /**
     * Generated from protobuf field <code>string app_company = 11;</code>
     */
    protected $app_company = '';
    /**
     * Generated from protobuf field <code>int32 target_type = 12;</code>
     */
    protected $target_type = 0;
    /**
     * Generated from protobuf field <code>int32 h5_jump_type = 13;</code>
     */
    protected $h5_jump_type = 0;
    /**
     * Generated from protobuf field <code>string h5_jump_number = 14;</code>
     */
    protected $h5_jump_number = '';
    /**
     * Generated from protobuf field <code>string h5_jump_param = 15;</code>
     */
    protected $h5_jump_param = '';
    /**
     * Generated from protobuf field <code>int32 jump_type = 16;</code>
     */
    protected $jump_type = 0;
    /**
     * Generated from protobuf field <code>string item_id = 17;</code>
     */
    protected $item_id = '';
    /**
     * Generated from protobuf field <code>int32 is_appoint = 18;</code>
     */
    protected $is_appoint = 0;
    /**
     * Generated from protobuf field <code>.tbClient.post.common.Content.TiebaPlusInfo.PluginUser plugin_user = 19;</code>
     */
    protected $plugin_user = null;
    /**
     * Generated from protobuf field <code>string forum_name = 20;</code>
     */
    protected $forum_name = '';
    /**
     * Generated from protobuf field <code>int32 jump_setting = 21;</code>
     */
    protected $jump_setting = 0;
    /**
     * Generated from protobuf field <code>string wx_thumbnail = 22;</code>
     */
    protected $wx_thumbnail = '';
    /**
     * Generated from protobuf field <code>string button_desc = 23;</code>
     */
    protected $button_desc = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $desc
     *     @type string $jump_url
     *     @type string $download_url
     *     @type string $app_id
     *     @type string $app_icon
     *     @type string $app_package
     *     @type string $app_version
     *     @type string $app_privacy
     *     @type string $app_power
     *     @type string $app_company
     *     @type int $target_type
     *     @type int $h5_jump_type
     *     @type string $h5_jump_number
     *     @type string $h5_jump_param
     *     @type int $jump_type
     *     @type string $item_id
     *     @type int $is_appoint
     *     @type \TbClient\Post\Common\Content\TiebaPlusInfo\PluginUser $plugin_user
     *     @type string $forum_name
     *     @type int $jump_setting
     *     @type string $wx_thumbnail
     *     @type string $button_desc
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Post\Common\Content::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string desc = 2;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>string desc = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jump_url = 3;</code>
     * @return string
     */
    public function getJumpUrl()
    {
        return $this->jump_url;
    }

    /**
     * Generated from protobuf field <code>string jump_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJumpUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->jump_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string download_url = 4;</code>
     * @return string
     */
    public function getDownloadUrl()
    {
        return $this->download_url;
    }

    /**
     * Generated from protobuf field <code>string download_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_id = 5;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>string app_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_icon = 6;</code>
     * @return string
     */
    public function getAppIcon()
    {
        return $this->app_icon;
    }

    /**
     * Generated from protobuf field <code>string app_icon = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAppIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_package = 7;</code>
     * @return string
     */
    public function getAppPackage()
    {
        return $this->app_package;
    }

    /**
     * Generated from protobuf field <code>string app_package = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAppPackage($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_version = 8;</code>
     * @return string
     */
    public function getAppVersion()
    {
        return $this->app_version;
    }

    /**
     * Generated from protobuf field <code>string app_version = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_privacy = 9;</code>
     * @return string
     */
    public function getAppPrivacy()
    {
        return $this->app_privacy;
    }

    /**
     * Generated from protobuf field <code>string app_privacy = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAppPrivacy($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_privacy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_power = 10;</code>
     * @return string
     */
    public function getAppPower()
    {
        return $this->app_power;
    }

    /**
     * Generated from protobuf field <code>string app_power = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAppPower($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_company = 11;</code>
     * @return string
     */
    public function getAppCompany()
    {
        return $this->app_company;
    }

    /**
     * Generated from protobuf field <code>string app_company = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setAppCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_company = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 target_type = 12;</code>
     * @return int
     */
    public function getTargetType()
    {
        return $this->target_type;
    }

    /**
     * Generated from protobuf field <code>int32 target_type = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setTargetType($var)
    {
        GPBUtil::checkInt32($var);
        $this->target_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 h5_jump_type = 13;</code>
     * @return int
     */
    public function getH5JumpType()
    {
        return $this->h5_jump_type;
    }

    /**
     * Generated from protobuf field <code>int32 h5_jump_type = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setH5JumpType($var)
    {
        GPBUtil::checkInt32($var);
        $this->h5_jump_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string h5_jump_number = 14;</code>
     * @return string
     */
    public function getH5JumpNumber()
    {
        return $this->h5_jump_number;
    }

    /**
     * Generated from protobuf field <code>string h5_jump_number = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setH5JumpNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->h5_jump_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string h5_jump_param = 15;</code>
     * @return string
     */
    public function getH5JumpParam()
    {
        return $this->h5_jump_param;
    }

    /**
     * Generated from protobuf field <code>string h5_jump_param = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setH5JumpParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->h5_jump_param = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 jump_type = 16;</code>
     * @return int
     */
    public function getJumpType()
    {
        return $this->jump_type;
    }

    /**
     * Generated from protobuf field <code>int32 jump_type = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setJumpType($var)
    {
        GPBUtil::checkInt32($var);
        $this->jump_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_id = 17;</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>string item_id = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 is_appoint = 18;</code>
     * @return int
     */
    public function getIsAppoint()
    {
        return $this->is_appoint;
    }

    /**
     * Generated from protobuf field <code>int32 is_appoint = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAppoint($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_appoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tbClient.post.common.Content.TiebaPlusInfo.PluginUser plugin_user = 19;</code>
     * @return \TbClient\Post\Common\Content\TiebaPlusInfo\PluginUser|null
     */
    public function getPluginUser()
    {
        return $this->plugin_user;
    }

    public function hasPluginUser()
    {
        return isset($this->plugin_user);
    }

    public function clearPluginUser()
    {
        unset($this->plugin_user);
    }

    /**
     * Generated from protobuf field <code>.tbClient.post.common.Content.TiebaPlusInfo.PluginUser plugin_user = 19;</code>
     * @param \TbClient\Post\Common\Content\TiebaPlusInfo\PluginUser $var
     * @return $this
     */
    public function setPluginUser($var)
    {
        GPBUtil::checkMessage($var, \TbClient\Post\Common\Content\TiebaPlusInfo\PluginUser::class);
        $this->plugin_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string forum_name = 20;</code>
     * @return string
     */
    public function getForumName()
    {
        return $this->forum_name;
    }

    /**
     * Generated from protobuf field <code>string forum_name = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setForumName($var)
    {
        GPBUtil::checkString($var, True);
        $this->forum_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 jump_setting = 21;</code>
     * @return int
     */
    public function getJumpSetting()
    {
        return $this->jump_setting;
    }

    /**
     * Generated from protobuf field <code>int32 jump_setting = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setJumpSetting($var)
    {
        GPBUtil::checkInt32($var);
        $this->jump_setting = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wx_thumbnail = 22;</code>
     * @return string
     */
    public function getWxThumbnail()
    {
        return $this->wx_thumbnail;
    }

    /**
     * Generated from protobuf field <code>string wx_thumbnail = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setWxThumbnail($var)
    {
        GPBUtil::checkString($var, True);
        $this->wx_thumbnail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string button_desc = 23;</code>
     * @return string
     */
    public function getButtonDesc()
    {
        return $this->button_desc;
    }

    /**
     * Generated from protobuf field <code>string button_desc = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setButtonDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->button_desc = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TiebaPlusInfo::class, \TbClient\Post\Common\Content_TiebaPlusInfo::class);

