// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Item/ApkDetail.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TbClient.Item {

  /// <summary>Holder for reflection information generated from Item/ApkDetail.proto</summary>
  public static partial class ApkDetailReflection {

    #region Descriptor
    /// <summary>File descriptor for Item/ApkDetail.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApkDetailReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRJdGVtL0Fwa0RldGFpbC5wcm90bxINdGJDbGllbnQuaXRlbSLpAQoJQXBr",
            "RGV0YWlsEhEKCWRldmVsb3BlchgBIAEoCRIRCglwdWJsaXNoZXIYAiABKAkS",
            "DwoHdmVyc2lvbhgDIAEoCRIUCgx2ZXJzaW9uX2NvZGUYBiABKAUSEwoLdXBk",
            "YXRlX3RpbWUYByABKAkSDAoEc2l6ZRgIIAEoCRIUCgxuZWVkX25ldHdvcmsY",
            "CSABKAUSFgoObmVlZF9pbm5lcl9idXkYCiABKAUSFQoNYXV0aG9yaXR5X3Vy",
            "bBgLIAEoCRITCgtwcml2YWN5X3VybBgMIAEoCRISCgpwa2dfc291cmNlGA0g",
            "ASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TbClient.Item.ApkDetail), global::TbClient.Item.ApkDetail.Parser, new[]{ "Developer", "Publisher", "Version", "VersionCode", "UpdateTime", "Size", "NeedNetwork", "NeedInnerBuy", "AuthorityUrl", "PrivacyUrl", "PkgSource" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApkDetail : pb::IMessage<ApkDetail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApkDetail> _parser = new pb::MessageParser<ApkDetail>(() => new ApkDetail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApkDetail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TbClient.Item.ApkDetailReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApkDetail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApkDetail(ApkDetail other) : this() {
      developer_ = other.developer_;
      publisher_ = other.publisher_;
      version_ = other.version_;
      versionCode_ = other.versionCode_;
      updateTime_ = other.updateTime_;
      size_ = other.size_;
      needNetwork_ = other.needNetwork_;
      needInnerBuy_ = other.needInnerBuy_;
      authorityUrl_ = other.authorityUrl_;
      privacyUrl_ = other.privacyUrl_;
      pkgSource_ = other.pkgSource_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApkDetail Clone() {
      return new ApkDetail(this);
    }

    /// <summary>Field number for the "developer" field.</summary>
    public const int DeveloperFieldNumber = 1;
    private string developer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Developer {
      get { return developer_; }
      set {
        developer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "publisher" field.</summary>
    public const int PublisherFieldNumber = 2;
    private string publisher_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Publisher {
      get { return publisher_; }
      set {
        publisher_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 3;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version_code" field.</summary>
    public const int VersionCodeFieldNumber = 6;
    private int versionCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VersionCode {
      get { return versionCode_; }
      set {
        versionCode_ = value;
      }
    }

    /// <summary>Field number for the "update_time" field.</summary>
    public const int UpdateTimeFieldNumber = 7;
    private string updateTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UpdateTime {
      get { return updateTime_; }
      set {
        updateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 8;
    private string size_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Size {
      get { return size_; }
      set {
        size_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "need_network" field.</summary>
    public const int NeedNetworkFieldNumber = 9;
    private int needNetwork_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NeedNetwork {
      get { return needNetwork_; }
      set {
        needNetwork_ = value;
      }
    }

    /// <summary>Field number for the "need_inner_buy" field.</summary>
    public const int NeedInnerBuyFieldNumber = 10;
    private int needInnerBuy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NeedInnerBuy {
      get { return needInnerBuy_; }
      set {
        needInnerBuy_ = value;
      }
    }

    /// <summary>Field number for the "authority_url" field.</summary>
    public const int AuthorityUrlFieldNumber = 11;
    private string authorityUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthorityUrl {
      get { return authorityUrl_; }
      set {
        authorityUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "privacy_url" field.</summary>
    public const int PrivacyUrlFieldNumber = 12;
    private string privacyUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PrivacyUrl {
      get { return privacyUrl_; }
      set {
        privacyUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pkg_source" field.</summary>
    public const int PkgSourceFieldNumber = 13;
    private int pkgSource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PkgSource {
      get { return pkgSource_; }
      set {
        pkgSource_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApkDetail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApkDetail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Developer != other.Developer) return false;
      if (Publisher != other.Publisher) return false;
      if (Version != other.Version) return false;
      if (VersionCode != other.VersionCode) return false;
      if (UpdateTime != other.UpdateTime) return false;
      if (Size != other.Size) return false;
      if (NeedNetwork != other.NeedNetwork) return false;
      if (NeedInnerBuy != other.NeedInnerBuy) return false;
      if (AuthorityUrl != other.AuthorityUrl) return false;
      if (PrivacyUrl != other.PrivacyUrl) return false;
      if (PkgSource != other.PkgSource) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Developer.Length != 0) hash ^= Developer.GetHashCode();
      if (Publisher.Length != 0) hash ^= Publisher.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (VersionCode != 0) hash ^= VersionCode.GetHashCode();
      if (UpdateTime.Length != 0) hash ^= UpdateTime.GetHashCode();
      if (Size.Length != 0) hash ^= Size.GetHashCode();
      if (NeedNetwork != 0) hash ^= NeedNetwork.GetHashCode();
      if (NeedInnerBuy != 0) hash ^= NeedInnerBuy.GetHashCode();
      if (AuthorityUrl.Length != 0) hash ^= AuthorityUrl.GetHashCode();
      if (PrivacyUrl.Length != 0) hash ^= PrivacyUrl.GetHashCode();
      if (PkgSource != 0) hash ^= PkgSource.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Developer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Developer);
      }
      if (Publisher.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Publisher);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Version);
      }
      if (VersionCode != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(VersionCode);
      }
      if (UpdateTime.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(UpdateTime);
      }
      if (Size.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Size);
      }
      if (NeedNetwork != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(NeedNetwork);
      }
      if (NeedInnerBuy != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(NeedInnerBuy);
      }
      if (AuthorityUrl.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(AuthorityUrl);
      }
      if (PrivacyUrl.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(PrivacyUrl);
      }
      if (PkgSource != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(PkgSource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Developer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Developer);
      }
      if (Publisher.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Publisher);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Version);
      }
      if (VersionCode != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(VersionCode);
      }
      if (UpdateTime.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(UpdateTime);
      }
      if (Size.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Size);
      }
      if (NeedNetwork != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(NeedNetwork);
      }
      if (NeedInnerBuy != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(NeedInnerBuy);
      }
      if (AuthorityUrl.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(AuthorityUrl);
      }
      if (PrivacyUrl.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(PrivacyUrl);
      }
      if (PkgSource != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(PkgSource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Developer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Developer);
      }
      if (Publisher.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Publisher);
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (VersionCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VersionCode);
      }
      if (UpdateTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpdateTime);
      }
      if (Size.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Size);
      }
      if (NeedNetwork != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NeedNetwork);
      }
      if (NeedInnerBuy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NeedInnerBuy);
      }
      if (AuthorityUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthorityUrl);
      }
      if (PrivacyUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrivacyUrl);
      }
      if (PkgSource != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PkgSource);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApkDetail other) {
      if (other == null) {
        return;
      }
      if (other.Developer.Length != 0) {
        Developer = other.Developer;
      }
      if (other.Publisher.Length != 0) {
        Publisher = other.Publisher;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.VersionCode != 0) {
        VersionCode = other.VersionCode;
      }
      if (other.UpdateTime.Length != 0) {
        UpdateTime = other.UpdateTime;
      }
      if (other.Size.Length != 0) {
        Size = other.Size;
      }
      if (other.NeedNetwork != 0) {
        NeedNetwork = other.NeedNetwork;
      }
      if (other.NeedInnerBuy != 0) {
        NeedInnerBuy = other.NeedInnerBuy;
      }
      if (other.AuthorityUrl.Length != 0) {
        AuthorityUrl = other.AuthorityUrl;
      }
      if (other.PrivacyUrl.Length != 0) {
        PrivacyUrl = other.PrivacyUrl;
      }
      if (other.PkgSource != 0) {
        PkgSource = other.PkgSource;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Developer = input.ReadString();
            break;
          }
          case 18: {
            Publisher = input.ReadString();
            break;
          }
          case 26: {
            Version = input.ReadString();
            break;
          }
          case 48: {
            VersionCode = input.ReadInt32();
            break;
          }
          case 58: {
            UpdateTime = input.ReadString();
            break;
          }
          case 66: {
            Size = input.ReadString();
            break;
          }
          case 72: {
            NeedNetwork = input.ReadInt32();
            break;
          }
          case 80: {
            NeedInnerBuy = input.ReadInt32();
            break;
          }
          case 90: {
            AuthorityUrl = input.ReadString();
            break;
          }
          case 98: {
            PrivacyUrl = input.ReadString();
            break;
          }
          case 104: {
            PkgSource = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Developer = input.ReadString();
            break;
          }
          case 18: {
            Publisher = input.ReadString();
            break;
          }
          case 26: {
            Version = input.ReadString();
            break;
          }
          case 48: {
            VersionCode = input.ReadInt32();
            break;
          }
          case 58: {
            UpdateTime = input.ReadString();
            break;
          }
          case 66: {
            Size = input.ReadString();
            break;
          }
          case 72: {
            NeedNetwork = input.ReadInt32();
            break;
          }
          case 80: {
            NeedInnerBuy = input.ReadInt32();
            break;
          }
          case 90: {
            AuthorityUrl = input.ReadString();
            break;
          }
          case 98: {
            PrivacyUrl = input.ReadString();
            break;
          }
          case 104: {
            PkgSource = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
