<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Api/Request/Common.proto

namespace GPBMetadata\Api\Request;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
[
Api/Request/Common.prototbClient.api.request"!
Common
_client_version (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

