<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserDeps/Icon.proto

namespace GPBMetadata\UserDeps;

class Icon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ô
UserDeps/Icon.prototbClient.userDeps"Á
Icon
name (	
weight (
url (	
icon (	
value (2
terminal (2 .tbClient.userDeps.Icon.Terminal2
position (2 .tbClient.userDeps.Icon.Position
sprite_info (	3
Terminal

pc (
wap (
client (?
Position
frs (

pb (
home (
card (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

