<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/Common/Content.proto

namespace TbClient\Post\Common;

if (false) {
    /**
     * This class is deprecated. Use TbClient\Post\Common\Content\TiebaPlusInfo\PluginUser instead.
     * @deprecated
     */
    class Content_TiebaPlusInfo_PluginUser {}
}
class_exists(Content\TiebaPlusInfo\PluginUser::class);
@trigger_error('TbClient\Post\Common\Content_TiebaPlusInfo_PluginUser is deprecated and will be removed in the next major release. Use TbClient\Post\Common\Content\TiebaPlusInfo\PluginUser instead', E_USER_DEPRECATED);

