<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/Common/Content.proto

namespace TbClient\Post\Common;

if (false) {
    /**
     * This class is deprecated. Use TbClient\Post\Common\Content\TiebaPlusInfo instead.
     * @deprecated
     */
    class Content_TiebaPlusInfo {}
}
class_exists(Content\TiebaPlusInfo::class);
@trigger_error('TbClient\Post\Common\Content_TiebaPlusInfo is deprecated and will be removed in the next major release. Use TbClient\Post\Common\Content\TiebaPlusInfo instead', E_USER_DEPRECATED);

