<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Post/Common/Zan.proto

namespace TbClient\Post\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.post.common.Zan</code>
 */
class Zan extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     */
    protected $num = 0;
    /**
     * Generated from protobuf field <code>repeated .tbClient.User liker_list = 2;</code>
     */
    private $liker_list;
    /**
     * Generated from protobuf field <code>int32 is_liked = 3;</code>
     */
    protected $is_liked = 0;
    /**
     * Generated from protobuf field <code>int32 last_time = 4;</code>
     */
    protected $last_time = 0;
    /**
     * Generated from protobuf field <code>repeated int64 liker_id = 5;</code>
     */
    private $liker_id;
    /**
     * Generated from protobuf field <code>int32 consent_type = 6;</code>
     */
    protected $consent_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $num
     *     @type array<\TbClient\User>|\Google\Protobuf\Internal\RepeatedField $liker_list
     *     @type int $is_liked
     *     @type int $last_time
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $liker_id
     *     @type int $consent_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Post\Common\Zan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     * @return int
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .tbClient.User liker_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLikerList()
    {
        return $this->liker_list;
    }

    /**
     * Generated from protobuf field <code>repeated .tbClient.User liker_list = 2;</code>
     * @param array<\TbClient\User>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLikerList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TbClient\User::class);
        $this->liker_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 is_liked = 3;</code>
     * @return int
     */
    public function getIsLiked()
    {
        return $this->is_liked;
    }

    /**
     * Generated from protobuf field <code>int32 is_liked = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLiked($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_liked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 last_time = 4;</code>
     * @return int
     */
    public function getLastTime()
    {
        return $this->last_time;
    }

    /**
     * Generated from protobuf field <code>int32 last_time = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLastTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 liker_id = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLikerId()
    {
        return $this->liker_id;
    }

    /**
     * Generated from protobuf field <code>repeated int64 liker_id = 5;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLikerId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->liker_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 consent_type = 6;</code>
     * @return int
     */
    public function getConsentType()
    {
        return $this->consent_type;
    }

    /**
     * Generated from protobuf field <code>int32 consent_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setConsentType($var)
    {
        GPBUtil::checkInt32($var);
        $this->consent_type = $var;

        return $this;
    }

}

