<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/Thread.proto

namespace TbClient\Post\Thread;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.post.Thread.Abstract</code>
 */
class PBAbstract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string text = 2;</code>
     */
    protected $text = '';
    /**
     * Generated from protobuf field <code>string link = 3;</code>
     */
    protected $link = '';
    /**
     * Generated from protobuf field <code>string src = 4;</code>
     */
    protected $src = '';
    /**
     * Generated from protobuf field <code>string un = 5;</code>
     */
    protected $un = '';
    /**
     * Generated from protobuf field <code>string during_time = 6;</code>
     */
    protected $during_time = '';
    /**
     * Generated from protobuf field <code>string voice_md5 = 7;</code>
     */
    protected $voice_md5 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $text
     *     @type string $link
     *     @type string $src
     *     @type string $un
     *     @type string $during_time
     *     @type string $voice_md5
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Post\Thread::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string link = 3;</code>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>string link = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string src = 4;</code>
     * @return string
     */
    public function getSrc()
    {
        return $this->src;
    }

    /**
     * Generated from protobuf field <code>string src = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSrc($var)
    {
        GPBUtil::checkString($var, True);
        $this->src = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string un = 5;</code>
     * @return string
     */
    public function getUn()
    {
        return $this->un;
    }

    /**
     * Generated from protobuf field <code>string un = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUn($var)
    {
        GPBUtil::checkString($var, True);
        $this->un = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string during_time = 6;</code>
     * @return string
     */
    public function getDuringTime()
    {
        return $this->during_time;
    }

    /**
     * Generated from protobuf field <code>string during_time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDuringTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->during_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string voice_md5 = 7;</code>
     * @return string
     */
    public function getVoiceMd5()
    {
        return $this->voice_md5;
    }

    /**
     * Generated from protobuf field <code>string voice_md5 = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVoiceMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->voice_md5 = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PBAbstract::class, \TbClient\Post\Thread_Abstract::class);

