<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Wrapper/ThreadAbstractWrapper.proto

namespace GPBMetadata\Wrapper;

class ThreadAbstractWrapper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Post\Common\PBAbstract::initOnce();
        $pool->internalAddGeneratedFile(
            '
‡
#Wrapper/ThreadAbstractWrapper.prototbClient.wrapper"F
ThreadAbstractWrapper-
value (2.tbClient.post.common.Abstractbproto3'
        , true);

        static::$is_initialized = true;
    }
}

