<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Wrapper/UserIconWrapper.proto

namespace GPBMetadata\Wrapper;

class UserIconWrapper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserDeps\Icon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0At\x0A\x1DWrapper/UserIconWrapper.proto\x12\x10tbClient.wrapper\"9\x0A\x0FUserIconWrapper\x12&\x0A\x05value\x18\x01 \x03(\x0B2\x17.tbClient.userDeps.Iconb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

