<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Api/Request/ThreadRequest.proto

namespace TbClient\Api\Request\ThreadRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.api.request.ThreadRequest.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string kw = 1;</code>
     */
    protected $kw = '';
    /**
     * Generated from protobuf field <code>int32 rn = 2;</code>
     */
    protected $rn = 0;
    /**
     * Generated from protobuf field <code>int32 rn_need = 3;</code>
     */
    protected $rn_need = 0;
    /**
     * Generated from protobuf field <code>int32 pn = 15;</code>
     */
    protected $pn = 0;
    /**
     * Generated from protobuf field <code>.tbClient.api.request.Common common = 39;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>int32 sort_type = 47;</code>
     */
    protected $sort_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $kw
     *     @type int $rn
     *     @type int $rn_need
     *     @type int $pn
     *     @type \TbClient\Api\Request\Common $common
     *     @type int $sort_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\Request\ThreadRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string kw = 1;</code>
     * @return string
     */
    public function getKw()
    {
        return $this->kw;
    }

    /**
     * Generated from protobuf field <code>string kw = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKw($var)
    {
        GPBUtil::checkString($var, True);
        $this->kw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rn = 2;</code>
     * @return int
     */
    public function getRn()
    {
        return $this->rn;
    }

    /**
     * Generated from protobuf field <code>int32 rn = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRn($var)
    {
        GPBUtil::checkInt32($var);
        $this->rn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rn_need = 3;</code>
     * @return int
     */
    public function getRnNeed()
    {
        return $this->rn_need;
    }

    /**
     * Generated from protobuf field <code>int32 rn_need = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRnNeed($var)
    {
        GPBUtil::checkInt32($var);
        $this->rn_need = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pn = 15;</code>
     * @return int
     */
    public function getPn()
    {
        return $this->pn;
    }

    /**
     * Generated from protobuf field <code>int32 pn = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setPn($var)
    {
        GPBUtil::checkInt32($var);
        $this->pn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tbClient.api.request.Common common = 39;</code>
     * @return \TbClient\Api\Request\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.tbClient.api.request.Common common = 39;</code>
     * @param \TbClient\Api\Request\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \TbClient\Api\Request\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sort_type = 47;</code>
     * @return int
     */
    public function getSortType()
    {
        return $this->sort_type;
    }

    /**
     * Generated from protobuf field <code>int32 sort_type = 47;</code>
     * @param int $var
     * @return $this
     */
    public function setSortType($var)
    {
        GPBUtil::checkInt32($var);
        $this->sort_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Data::class, \TbClient\Api\Request\ThreadRequest_Data::class);

