// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserDeps/BaijiahaoInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TbClient.UserDeps {

  /// <summary>Holder for reflection information generated from UserDeps/BaijiahaoInfo.proto</summary>
  public static partial class BaijiahaoInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for UserDeps/BaijiahaoInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BaijiahaoInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxVc2VyRGVwcy9CYWlqaWFoYW9JbmZvLnByb3RvEhF0YkNsaWVudC51c2Vy",
            "RGVwcyKNAQoNQmFpamlhaGFvSW5mbxIMCgRuYW1lGAEgASgJEg4KBmF2YXRh",
            "chgCIAEoCRIQCghhdmF0YXJfaBgDIAEoCRINCgVicmllZhgEIAEoCRIPCgdh",
            "dXRoX2lkGAUgASgFEhEKCWF1dGhfZGVzYxgGIAEoCRIZChFjYW5fbW9kaWZ5",
            "X2F2YXRhchgHIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TbClient.UserDeps.BaijiahaoInfo), global::TbClient.UserDeps.BaijiahaoInfo.Parser, new[]{ "Name", "Avatar", "AvatarH", "Brief", "AuthId", "AuthDesc", "CanModifyAvatar" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BaijiahaoInfo : pb::IMessage<BaijiahaoInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaijiahaoInfo> _parser = new pb::MessageParser<BaijiahaoInfo>(() => new BaijiahaoInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaijiahaoInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TbClient.UserDeps.BaijiahaoInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaijiahaoInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaijiahaoInfo(BaijiahaoInfo other) : this() {
      name_ = other.name_;
      avatar_ = other.avatar_;
      avatarH_ = other.avatarH_;
      brief_ = other.brief_;
      authId_ = other.authId_;
      authDesc_ = other.authDesc_;
      canModifyAvatar_ = other.canModifyAvatar_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaijiahaoInfo Clone() {
      return new BaijiahaoInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 2;
    private string avatar_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Avatar {
      get { return avatar_; }
      set {
        avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_h" field.</summary>
    public const int AvatarHFieldNumber = 3;
    private string avatarH_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AvatarH {
      get { return avatarH_; }
      set {
        avatarH_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "brief" field.</summary>
    public const int BriefFieldNumber = 4;
    private string brief_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Brief {
      get { return brief_; }
      set {
        brief_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auth_id" field.</summary>
    public const int AuthIdFieldNumber = 5;
    private int authId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AuthId {
      get { return authId_; }
      set {
        authId_ = value;
      }
    }

    /// <summary>Field number for the "auth_desc" field.</summary>
    public const int AuthDescFieldNumber = 6;
    private string authDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthDesc {
      get { return authDesc_; }
      set {
        authDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "can_modify_avatar" field.</summary>
    public const int CanModifyAvatarFieldNumber = 7;
    private int canModifyAvatar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CanModifyAvatar {
      get { return canModifyAvatar_; }
      set {
        canModifyAvatar_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaijiahaoInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaijiahaoInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Avatar != other.Avatar) return false;
      if (AvatarH != other.AvatarH) return false;
      if (Brief != other.Brief) return false;
      if (AuthId != other.AuthId) return false;
      if (AuthDesc != other.AuthDesc) return false;
      if (CanModifyAvatar != other.CanModifyAvatar) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
      if (AvatarH.Length != 0) hash ^= AvatarH.GetHashCode();
      if (Brief.Length != 0) hash ^= Brief.GetHashCode();
      if (AuthId != 0) hash ^= AuthId.GetHashCode();
      if (AuthDesc.Length != 0) hash ^= AuthDesc.GetHashCode();
      if (CanModifyAvatar != 0) hash ^= CanModifyAvatar.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Avatar);
      }
      if (AvatarH.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AvatarH);
      }
      if (Brief.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Brief);
      }
      if (AuthId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AuthId);
      }
      if (AuthDesc.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AuthDesc);
      }
      if (CanModifyAvatar != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CanModifyAvatar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Avatar);
      }
      if (AvatarH.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AvatarH);
      }
      if (Brief.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Brief);
      }
      if (AuthId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AuthId);
      }
      if (AuthDesc.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AuthDesc);
      }
      if (CanModifyAvatar != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CanModifyAvatar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Avatar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
      }
      if (AvatarH.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarH);
      }
      if (Brief.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Brief);
      }
      if (AuthId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AuthId);
      }
      if (AuthDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthDesc);
      }
      if (CanModifyAvatar != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CanModifyAvatar);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaijiahaoInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Avatar.Length != 0) {
        Avatar = other.Avatar;
      }
      if (other.AvatarH.Length != 0) {
        AvatarH = other.AvatarH;
      }
      if (other.Brief.Length != 0) {
        Brief = other.Brief;
      }
      if (other.AuthId != 0) {
        AuthId = other.AuthId;
      }
      if (other.AuthDesc.Length != 0) {
        AuthDesc = other.AuthDesc;
      }
      if (other.CanModifyAvatar != 0) {
        CanModifyAvatar = other.CanModifyAvatar;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Avatar = input.ReadString();
            break;
          }
          case 26: {
            AvatarH = input.ReadString();
            break;
          }
          case 34: {
            Brief = input.ReadString();
            break;
          }
          case 40: {
            AuthId = input.ReadInt32();
            break;
          }
          case 50: {
            AuthDesc = input.ReadString();
            break;
          }
          case 56: {
            CanModifyAvatar = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Avatar = input.ReadString();
            break;
          }
          case 26: {
            AvatarH = input.ReadString();
            break;
          }
          case 34: {
            Brief = input.ReadString();
            break;
          }
          case 40: {
            AuthId = input.ReadInt32();
            break;
          }
          case 50: {
            AuthDesc = input.ReadString();
            break;
          }
          case 56: {
            CanModifyAvatar = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
