// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserDeps/PayMemberInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TbClient.UserDeps {

  /// <summary>Holder for reflection information generated from UserDeps/PayMemberInfo.proto</summary>
  public static partial class PayMemberInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for UserDeps/PayMemberInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PayMemberInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxVc2VyRGVwcy9QYXlNZW1iZXJJbmZvLnByb3RvEhF0YkNsaWVudC51c2Vy",
            "RGVwcyJoCg1QYXlNZW1iZXJJbmZvEhAKCHByb3BzX2lkGAEgASgFEhAKCGVu",
            "ZF90aW1lGAIgASgFEgsKA3VybBgDIAEoCRIVCg1leHBpcmVfcmVtaW5kGAQg",
            "ASgJEg8KB3BpY191cmwYBSABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TbClient.UserDeps.PayMemberInfo), global::TbClient.UserDeps.PayMemberInfo.Parser, new[]{ "PropsId", "EndTime", "Url", "ExpireRemind", "PicUrl" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PayMemberInfo : pb::IMessage<PayMemberInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayMemberInfo> _parser = new pb::MessageParser<PayMemberInfo>(() => new PayMemberInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayMemberInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TbClient.UserDeps.PayMemberInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayMemberInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayMemberInfo(PayMemberInfo other) : this() {
      propsId_ = other.propsId_;
      endTime_ = other.endTime_;
      url_ = other.url_;
      expireRemind_ = other.expireRemind_;
      picUrl_ = other.picUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayMemberInfo Clone() {
      return new PayMemberInfo(this);
    }

    /// <summary>Field number for the "props_id" field.</summary>
    public const int PropsIdFieldNumber = 1;
    private int propsId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PropsId {
      get { return propsId_; }
      set {
        propsId_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 2;
    private int endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 3;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expire_remind" field.</summary>
    public const int ExpireRemindFieldNumber = 4;
    private string expireRemind_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExpireRemind {
      get { return expireRemind_; }
      set {
        expireRemind_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pic_url" field.</summary>
    public const int PicUrlFieldNumber = 5;
    private string picUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PicUrl {
      get { return picUrl_; }
      set {
        picUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayMemberInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayMemberInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PropsId != other.PropsId) return false;
      if (EndTime != other.EndTime) return false;
      if (Url != other.Url) return false;
      if (ExpireRemind != other.ExpireRemind) return false;
      if (PicUrl != other.PicUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PropsId != 0) hash ^= PropsId.GetHashCode();
      if (EndTime != 0) hash ^= EndTime.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (ExpireRemind.Length != 0) hash ^= ExpireRemind.GetHashCode();
      if (PicUrl.Length != 0) hash ^= PicUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PropsId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PropsId);
      }
      if (EndTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EndTime);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Url);
      }
      if (ExpireRemind.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpireRemind);
      }
      if (PicUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PicUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PropsId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PropsId);
      }
      if (EndTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EndTime);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Url);
      }
      if (ExpireRemind.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpireRemind);
      }
      if (PicUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PicUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PropsId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PropsId);
      }
      if (EndTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndTime);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (ExpireRemind.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExpireRemind);
      }
      if (PicUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PicUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayMemberInfo other) {
      if (other == null) {
        return;
      }
      if (other.PropsId != 0) {
        PropsId = other.PropsId;
      }
      if (other.EndTime != 0) {
        EndTime = other.EndTime;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.ExpireRemind.Length != 0) {
        ExpireRemind = other.ExpireRemind;
      }
      if (other.PicUrl.Length != 0) {
        PicUrl = other.PicUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PropsId = input.ReadInt32();
            break;
          }
          case 16: {
            EndTime = input.ReadInt32();
            break;
          }
          case 26: {
            Url = input.ReadString();
            break;
          }
          case 34: {
            ExpireRemind = input.ReadString();
            break;
          }
          case 42: {
            PicUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PropsId = input.ReadInt32();
            break;
          }
          case 16: {
            EndTime = input.ReadInt32();
            break;
          }
          case 26: {
            Url = input.ReadString();
            break;
          }
          case 34: {
            ExpireRemind = input.ReadString();
            break;
          }
          case 42: {
            PicUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
