<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Item/ApkDetail.proto

namespace TbClient\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.item.ApkDetail</code>
 */
class ApkDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string developer = 1;</code>
     */
    protected $developer = '';
    /**
     * Generated from protobuf field <code>string publisher = 2;</code>
     */
    protected $publisher = '';
    /**
     * Generated from protobuf field <code>string version = 3;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>int32 version_code = 6;</code>
     */
    protected $version_code = 0;
    /**
     * Generated from protobuf field <code>string update_time = 7;</code>
     */
    protected $update_time = '';
    /**
     * Generated from protobuf field <code>string size = 8;</code>
     */
    protected $size = '';
    /**
     * Generated from protobuf field <code>int32 need_network = 9;</code>
     */
    protected $need_network = 0;
    /**
     * Generated from protobuf field <code>int32 need_inner_buy = 10;</code>
     */
    protected $need_inner_buy = 0;
    /**
     * Generated from protobuf field <code>string authority_url = 11;</code>
     */
    protected $authority_url = '';
    /**
     * Generated from protobuf field <code>string privacy_url = 12;</code>
     */
    protected $privacy_url = '';
    /**
     * Generated from protobuf field <code>int32 pkg_source = 13;</code>
     */
    protected $pkg_source = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $developer
     *     @type string $publisher
     *     @type string $version
     *     @type int $version_code
     *     @type string $update_time
     *     @type string $size
     *     @type int $need_network
     *     @type int $need_inner_buy
     *     @type string $authority_url
     *     @type string $privacy_url
     *     @type int $pkg_source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Item\ApkDetail::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string developer = 1;</code>
     * @return string
     */
    public function getDeveloper()
    {
        return $this->developer;
    }

    /**
     * Generated from protobuf field <code>string developer = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeveloper($var)
    {
        GPBUtil::checkString($var, True);
        $this->developer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publisher = 2;</code>
     * @return string
     */
    public function getPublisher()
    {
        return $this->publisher;
    }

    /**
     * Generated from protobuf field <code>string publisher = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisher($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 3;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version_code = 6;</code>
     * @return int
     */
    public function getVersionCode()
    {
        return $this->version_code;
    }

    /**
     * Generated from protobuf field <code>int32 version_code = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->version_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string update_time = 7;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>string update_time = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string size = 8;</code>
     * @return string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>string size = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 need_network = 9;</code>
     * @return int
     */
    public function getNeedNetwork()
    {
        return $this->need_network;
    }

    /**
     * Generated from protobuf field <code>int32 need_network = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setNeedNetwork($var)
    {
        GPBUtil::checkInt32($var);
        $this->need_network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 need_inner_buy = 10;</code>
     * @return int
     */
    public function getNeedInnerBuy()
    {
        return $this->need_inner_buy;
    }

    /**
     * Generated from protobuf field <code>int32 need_inner_buy = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setNeedInnerBuy($var)
    {
        GPBUtil::checkInt32($var);
        $this->need_inner_buy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string authority_url = 11;</code>
     * @return string
     */
    public function getAuthorityUrl()
    {
        return $this->authority_url;
    }

    /**
     * Generated from protobuf field <code>string authority_url = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorityUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->authority_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string privacy_url = 12;</code>
     * @return string
     */
    public function getPrivacyUrl()
    {
        return $this->privacy_url;
    }

    /**
     * Generated from protobuf field <code>string privacy_url = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivacyUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->privacy_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pkg_source = 13;</code>
     * @return int
     */
    public function getPkgSource()
    {
        return $this->pkg_source;
    }

    /**
     * Generated from protobuf field <code>int32 pkg_source = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setPkgSource($var)
    {
        GPBUtil::checkInt32($var);
        $this->pkg_source = $var;

        return $this;
    }

}

