<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post/ReplyDeps/SignatureData.proto

namespace TbClient\Post\ReplyDeps;

if (false) {
    /**
     * This class is deprecated. Use TbClient\Post\ReplyDeps\SignatureData\SignatureContent instead.
     * @deprecated
     */
    class SignatureData_SignatureContent {}
}
class_exists(SignatureData\SignatureContent::class);
@trigger_error('TbClient\Post\ReplyDeps\SignatureData_SignatureContent is deprecated and will be removed in the next major release. Use TbClient\Post\ReplyDeps\SignatureData\SignatureContent instead', E_USER_DEPRECATED);

