<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Wrapper/PostContentWrapper.proto

namespace GPBMetadata\Wrapper;

class PostContentWrapper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Post\Common\Content::initOnce();
        $pool->internalAddGeneratedFile(
            '
€
 Wrapper/PostContentWrapper.prototbClient.wrapper"B
PostContentWrapper,
value (2.tbClient.post.common.Contentbproto3'
        , true);

        static::$is_initialized = true;
    }
}

