<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Revision/ThreadRevisionNullFields.proto

namespace TbClient\Revision;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.revision.ThreadRevisionNullFields</code>
 */
class ThreadRevisionNullFields extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool stickyType = 2;</code>
     */
    protected $stickyType = false;
    /**
     * Generated from protobuf field <code>bool topicType = 3;</code>
     */
    protected $topicType = false;
    /**
     * Generated from protobuf field <code>bool isGood = 4;</code>
     */
    protected $isGood = false;
    /**
     * Generated from protobuf field <code>bool authorManagerType = 5;</code>
     */
    protected $authorManagerType = false;
    /**
     * Generated from protobuf field <code>bool latestReplierUid = 7;</code>
     */
    protected $latestReplierUid = false;
    /**
     * Generated from protobuf field <code>bool replyNum = 8;</code>
     */
    protected $replyNum = false;
    /**
     * Generated from protobuf field <code>bool viewNum = 9;</code>
     */
    protected $viewNum = false;
    /**
     * Generated from protobuf field <code>bool shareNum = 10;</code>
     */
    protected $shareNum = false;
    /**
     * Generated from protobuf field <code>bool agreeNum = 11;</code>
     */
    protected $agreeNum = false;
    /**
     * Generated from protobuf field <code>bool disagreeNum = 12;</code>
     */
    protected $disagreeNum = false;
    /**
     * Generated from protobuf field <code>bool location = 13;</code>
     */
    protected $location = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $stickyType
     *     @type bool $topicType
     *     @type bool $isGood
     *     @type bool $authorManagerType
     *     @type bool $latestReplierUid
     *     @type bool $replyNum
     *     @type bool $viewNum
     *     @type bool $shareNum
     *     @type bool $agreeNum
     *     @type bool $disagreeNum
     *     @type bool $location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Revision\ThreadRevisionNullFields::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool stickyType = 2;</code>
     * @return bool
     */
    public function getStickyType()
    {
        return $this->stickyType;
    }

    /**
     * Generated from protobuf field <code>bool stickyType = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setStickyType($var)
    {
        GPBUtil::checkBool($var);
        $this->stickyType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool topicType = 3;</code>
     * @return bool
     */
    public function getTopicType()
    {
        return $this->topicType;
    }

    /**
     * Generated from protobuf field <code>bool topicType = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setTopicType($var)
    {
        GPBUtil::checkBool($var);
        $this->topicType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isGood = 4;</code>
     * @return bool
     */
    public function getIsGood()
    {
        return $this->isGood;
    }

    /**
     * Generated from protobuf field <code>bool isGood = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsGood($var)
    {
        GPBUtil::checkBool($var);
        $this->isGood = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool authorManagerType = 5;</code>
     * @return bool
     */
    public function getAuthorManagerType()
    {
        return $this->authorManagerType;
    }

    /**
     * Generated from protobuf field <code>bool authorManagerType = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAuthorManagerType($var)
    {
        GPBUtil::checkBool($var);
        $this->authorManagerType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool latestReplierUid = 7;</code>
     * @return bool
     */
    public function getLatestReplierUid()
    {
        return $this->latestReplierUid;
    }

    /**
     * Generated from protobuf field <code>bool latestReplierUid = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setLatestReplierUid($var)
    {
        GPBUtil::checkBool($var);
        $this->latestReplierUid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replyNum = 8;</code>
     * @return bool
     */
    public function getReplyNum()
    {
        return $this->replyNum;
    }

    /**
     * Generated from protobuf field <code>bool replyNum = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setReplyNum($var)
    {
        GPBUtil::checkBool($var);
        $this->replyNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool viewNum = 9;</code>
     * @return bool
     */
    public function getViewNum()
    {
        return $this->viewNum;
    }

    /**
     * Generated from protobuf field <code>bool viewNum = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setViewNum($var)
    {
        GPBUtil::checkBool($var);
        $this->viewNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool shareNum = 10;</code>
     * @return bool
     */
    public function getShareNum()
    {
        return $this->shareNum;
    }

    /**
     * Generated from protobuf field <code>bool shareNum = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setShareNum($var)
    {
        GPBUtil::checkBool($var);
        $this->shareNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool agreeNum = 11;</code>
     * @return bool
     */
    public function getAgreeNum()
    {
        return $this->agreeNum;
    }

    /**
     * Generated from protobuf field <code>bool agreeNum = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setAgreeNum($var)
    {
        GPBUtil::checkBool($var);
        $this->agreeNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool disagreeNum = 12;</code>
     * @return bool
     */
    public function getDisagreeNum()
    {
        return $this->disagreeNum;
    }

    /**
     * Generated from protobuf field <code>bool disagreeNum = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisagreeNum($var)
    {
        GPBUtil::checkBool($var);
        $this->disagreeNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool location = 13;</code>
     * @return bool
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>bool location = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkBool($var);
        $this->location = $var;

        return $this;
    }

}

