<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Revision/UserRevisionNullFields.proto

namespace TbClient\Revision;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tbClient.revision.UserRevisionNullFields</code>
 */
class UserRevisionNullFields extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool name = 1;</code>
     */
    protected $name = false;
    /**
     * Generated from protobuf field <code>bool displayName = 2;</code>
     */
    protected $displayName = false;
    /**
     * Generated from protobuf field <code>bool portrait = 3;</code>
     */
    protected $portrait = false;
    /**
     * Generated from protobuf field <code>bool portraitUpdateTime = 7;</code>
     */
    protected $portraitUpdateTime = false;
    /**
     * Generated from protobuf field <code>bool gender = 4;</code>
     */
    protected $gender = false;
    /**
     * Generated from protobuf field <code>bool fansNickname = 5;</code>
     */
    protected $fansNickname = false;
    /**
     * Generated from protobuf field <code>bool iconInfo = 6;</code>
     */
    protected $iconInfo = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $name
     *     @type bool $displayName
     *     @type bool $portrait
     *     @type bool $portraitUpdateTime
     *     @type bool $gender
     *     @type bool $fansNickname
     *     @type bool $iconInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Revision\UserRevisionNullFields::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool name = 1;</code>
     * @return bool
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>bool name = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkBool($var);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool displayName = 2;</code>
     * @return bool
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * Generated from protobuf field <code>bool displayName = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkBool($var);
        $this->displayName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool portrait = 3;</code>
     * @return bool
     */
    public function getPortrait()
    {
        return $this->portrait;
    }

    /**
     * Generated from protobuf field <code>bool portrait = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPortrait($var)
    {
        GPBUtil::checkBool($var);
        $this->portrait = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool portraitUpdateTime = 7;</code>
     * @return bool
     */
    public function getPortraitUpdateTime()
    {
        return $this->portraitUpdateTime;
    }

    /**
     * Generated from protobuf field <code>bool portraitUpdateTime = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setPortraitUpdateTime($var)
    {
        GPBUtil::checkBool($var);
        $this->portraitUpdateTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool gender = 4;</code>
     * @return bool
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>bool gender = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkBool($var);
        $this->gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool fansNickname = 5;</code>
     * @return bool
     */
    public function getFansNickname()
    {
        return $this->fansNickname;
    }

    /**
     * Generated from protobuf field <code>bool fansNickname = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFansNickname($var)
    {
        GPBUtil::checkBool($var);
        $this->fansNickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool iconInfo = 6;</code>
     * @return bool
     */
    public function getIconInfo()
    {
        return $this->iconInfo;
    }

    /**
     * Generated from protobuf field <code>bool iconInfo = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIconInfo($var)
    {
        GPBUtil::checkBool($var);
        $this->iconInfo = $var;

        return $this;
    }

}

