<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Api/Response/ThreadResponse.proto

namespace TbClient\Api\Response;

if (false) {
    /**
     * This class is deprecated. Use TbClient\Api\Response\ThreadResponse\Data instead.
     * @deprecated
     */
    class ThreadResponse_Data {}
}
class_exists(ThreadResponse\Data::class);
@trigger_error('TbClient\Api\Response\ThreadResponse_Data is deprecated and will be removed in the next major release. Use TbClient\Api\Response\ThreadResponse\Data instead', E_USER_DEPRECATED);

